modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/Retraining/issues"
license="MIT"

[[mods]]
modId="retraining"
version="${file.jarVersion}"
displayName="Retraining"
displayURL="https://www.curseforge.com/minecraft/mc-mods/retraining"
authors="Mrbysco, ShyNieke"
description='''
Recycle your villager trades today :D
'''
[[dependencies.retraining]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"