# Project
version=3.3.0
group=com.mrbysco.retraining

# Common
minecraft_version=1.21.7

# NeoForge
neo_version=21.7.1-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.6
neogradle.subsystems.parchment.mappingsVersion=2025.06.29
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.128.1+1.21.7
fabric_loader_version=0.16.14

# Mod options
mod_name=Retraining
mod_author=Mrbysco
mod_id=retraining

#Publishing
curseforge_id=543209
modrinth_id=Iugiwphr

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false