# Project
version=3.0.0
group=com.mrbysco.retraining

# Common
minecraft_version=1.21.4

# NeoForge
neo_version=21.4.123
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.119.2+1.21.4
fabric_loader_version=0.16.10

# Mod options
mod_name=Retraining
mod_author=Mrbysco
mod_id=retraining

#Publishing
curseforge_id=543209
modrinth_id=Iugiwphr

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false