modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Retraining/issues"
license="MIT"

[[mods]]
modId="retraining"
version="${file.jarVersion}"
displayName="Retraining"
displayURL="https://www.curseforge.com/minecraft/mc-mods/retraining"
authors="Mrbysco, ShyNieke"
description='''
Recycle your villager trades today :D
'''
[[dependencies.retraining]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "retraining.mixins.json"