modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Retraining/issues"
license="MIT"

[[mods]]
modId="retraining"
version="${file.jarVersion}"
displayName="Retraining"
displayURL="https://www.curseforge.com/minecraft/mc-mods/retraining"
authors="Mrbysco, ShyNieke"
description='''
Recycle your villager trades today :D
'''
[[dependencies.retraining]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.retraining]]
modId="neoforge"
type="required"
versionRange="[21.11.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="retraining.mixins.json"